### ISSUE TITLE
addition of forloop.

### ISSUE THREAD

**Issue by Ritikkrpatel** [Ritikkrpatel/don-t-do-that-#12]
add some addition features of for loop.
[https://github.com/Ritikkrpatel/don-t-do-that-/blob/main/forloop.cpp](url)

**Comment by saurabh15april** [comment]
I want to work on it.
@Ritikkrpatel

**Comment by Ritikkrpatel** [comment]
okey!

**Comment by saurabh15april** [comment]
Done.
