### ISSUE TITLE
change triangle area in some new feature.

### ISSUE THREAD

**Issue by Ritikkrpatel** [Ritikkrpatel/don-t-do-that-#6]
change take input format into as long as possible.

**Comment by saurabh15april** [comment]
@Ritikkrpatel  I want to work on it.
will u pls assign me it?

**Comment by Ritikkrpatel** [comment]
ya sure, if u can.

**Comment by Ritikkrpatel** [comment]
ya sure @SaurabhDubey57, if u can.
